// generated by goassest(0.3 20150830)
// https://github.com/hidu/goassest/

package res

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"flag"
	"fmt"
	"io/ioutil"
	"mime"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"
)

// AssestFile assest file  struct
type AssestFile struct {
	Name    string
	Mtime   int64
	Content string
}

// AssestStruct assest files
type AssestStruct struct {
	Files map[string]*AssestFile
}

var _assestDirect bool

func init() {
	exeName := filepath.Base(os.Getenv("_"))
	//only enable with go run
	if exeName == "go" || exeName == "go.exe" {
		flag.BoolVar(&_assestDirect, "assest_direct", false, "for debug,read assest direct")
	}
}

var _assestCwd, _ = os.Getwd()

// GetAssestFile get file by name
func (statics *AssestStruct) GetAssestFile(name string) (*AssestFile, error) {
	name = strings.TrimLeft(path.Clean(name), "/")
	if _assestDirect {
		f, err := os.Open(_assestCwd + string(filepath.Separator) + name)
		if err != nil {
			return nil, err
		}
		defer f.Close()
		info, err := f.Stat()
		if err != nil {
			return nil, err
		}
		if info.Mode().IsRegular() {
			content, err := ioutil.ReadAll(f)
			if err != nil {
				return nil, err
			}
			return &AssestFile{
				Content: string(content),
				Name:    name,
				Mtime:   info.ModTime().Unix(),
			}, nil
		}
		return nil, fmt.Errorf("not file")
	}
	if sf, has := statics.Files[name]; has {
		return sf, nil
	}
	return nil, fmt.Errorf("not exists")
}

// GetContent get content by name
func (statics AssestStruct) GetContent(name string) string {
	s, err := statics.GetAssestFile(name)
	if err != nil {
		return ""
	}
	return s.Content
}

// GetFileNames get all file names
func (statics AssestStruct) GetFileNames(dir string) []string {
	names := make([]string, len(statics.Files))
	for name := range statics.Files {
		names = append(names, name)
	}
	return names
}

// FileHandlerFunc handler http files
func (statics *AssestStruct) FileHandlerFunc(name string) http.HandlerFunc {
	if strings.Contains(name, "private") {
		return http.NotFound
	}
	static, err := statics.GetAssestFile(name)
	return func(w http.ResponseWriter, r *http.Request) {
		if err != nil {
			http.NotFound(w, r)
			return
		}
		modtime := time.Unix(static.Mtime, 0)
		modifiedSince := r.Header.Get("If-Modified-Since")
		if modifiedSince != "" {
			t, err := time.Parse(http.TimeFormat, modifiedSince)
			if err == nil && modtime.Before(t.Add(1*time.Second)) {
				w.Header().Del("Content-Type")
				w.Header().Del("Content-Length")
				w.Header().Set("Last-Modified", modtime.UTC().Format(http.TimeFormat))
				w.WriteHeader(http.StatusNotModified)
				return
			}
		}

		mimeType := mime.TypeByExtension(filepath.Ext(static.Name))
		if mimeType != "" {
			w.Header().Set("Content-Type", mimeType)
		}
		w.Header().Set("Last-Modified", modtime.UTC().Format(http.TimeFormat))
		w.Write([]byte(static.Content))
	}
}

// HTTPHandler handler http request
// eg: http.Handle("/res/",res.Assest.HttpHandler("/res/"))
func (statics *AssestStruct) HTTPHandler(pdir string) http.Handler {
	return &_assestFileServer{sf: statics, pdir: pdir}
}

type _assestFileServer struct {
	sf   *AssestStruct
	pdir string
}

// ServeHTTP ServeHTTP
func (f *_assestFileServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	rname, _ := filepath.Rel(f.pdir, r.URL.Path)
	if filepath.Separator != '/' {
		rname = strings.Replace(rname, string(filepath.Separator), "/", -1)
	}
	f.sf.FileHandlerFunc(rname).ServeHTTP(w, r)
}

func _assestGzipBase64decode(data string) string {
	b, _ := base64.StdEncoding.DecodeString(data)
	gr, _ := gzip.NewReader(bytes.NewBuffer(b))
	bs, _ := ioutil.ReadAll(gr)
	return string(bs)
}

func _assestBase64Decode(data string) string {
	b, _ := base64.StdEncoding.DecodeString(data)
	return string(b)
}

// Assest export assests
var Assest = &AssestStruct{
	Files: map[string]*AssestFile{

		_assestBase64Decode("cmVzL2IuY3Nz"): {
			Name:    _assestBase64Decode("cmVzL2IuY3Nz"),
			Mtime:   1440515205,
			Content: _assestGzipBase64decode("H4sIAAAJbogA/8owrE7LzyvRLc6sSrVSMLEoqLBOzs/JL7JKL0pNzavl4sowroYIFKWmWNdyZZggcwEAAAD//wEAAP//Ce8a8z4AAAA="),
		},

		_assestBase64Decode("cmVzL2luZGV4Lmh0bWw="): {
			Name:    _assestBase64Decode("cmVzL2luZGV4Lmh0bWw="),
			Mtime:   1440515205,
			Content: _assestGzipBase64decode("H4sIAAAJbogA/5SRu27zMAyF9zwFo93Rn8vwD7KWXtZ2SIdOBWOzkRMlMkSird++9KWA0S7tJOCQ5/Dgk1vePtzsnx/vIMgl+oX7eghrfS4kCFXAzCSledrfF/+NytJIJB8oxgTITCzOjtrCxeZ6hkyxNCxdJA5EYkC6lkoj9CG2YjYQMr2WxmZie1j1ijq5yk0r89UTvuGoGuBcTYYTW1yd1OLsOPyDd2YCtywK2P3bQVH8MqHFI6lhHvItxU7gDqnu/EI5ridM7ynHWsdrHbbe4U8CIJiPPeaXQ8Tr2fhBdhb1WqtZGrbxxzTyhpouSeM2w5EtNHVphkN9t7D1Q6ueElTpKnobGpkajtV0q//pTwAAAP//AQAA//8lBkWbAAIAAA=="),
		},

		_assestBase64Decode("cmVzL2pzL2EuanM="): {
			Name:    _assestBase64Decode("cmVzL2pzL2EuanM="),
			Mtime:   1440515205,
			Content: _assestGzipBase64decode("H4sIAAAJbogA/+IqTi0JycxNzS8t0UgrzUsuyczP09Cs5uJMyU8uzU3NK9FLTy1xzUkFMZ0qPVM0lDJSc3LylTT1MvPyUos8Qnx9bCFCOol6WcUKRkrWXLU6hgYGBprWAAAAAP//AQAA//9NRg/0XAAAAA=="),
		},
	},
}
