// Generated by goasset(1.0 20200425) or "go generate" . DO NOT EDIT.
// https://github.com/hidu/goasset/

package internal

import (
	"reflect"
	"sort"
	"testing"
)

func TestAsset(t *testing.T) {
	got := Asset.GetFileNames("/")
	sort.Slice(got, func(i, j int) bool {
		return got[i] < got[j]
	})
	want := []string{

		"/template/asset_test.tpl",

		"/template/asset_tpl.go",

		"/template/demo_config.json",

		"/template/footer.tpl",

		"/template/footer_fn.go",

		"/template/header.tpl",

		"/template/helper.go",

		"/template/helper_test.go",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Asset.GetFileNames(\"/\")=\n%v, want=\n%v", got, want)
	}
}
